server:
  port: 8888

spring:
  application:
    name: microservice-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password